language: node_js
node_js:
  - 'lts/dubnium'

cache: yarn

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - ng build --prod

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_failure: always
    on_success: change

deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh production
    on:
      branch: master
