language: node_js
node_js:
  - "6.9"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - ./deploy.sh

notifications:
  email:
    on_failure: $EMAIL
    on_success: $EMAIL
