language: node_js
node_js:
  - "9.9"

cache: yarn

before_script:
  - yarn add global firebase-tools
  - yarn add global @angular/cli

script:
  - ng build --prod

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_failure: $EMAIL
    on_success: $EMAIL

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash ./deploy.sh staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash ./deploy.sh production
    on:
      branch: master
