language: node_js
node_js:
  - "9.9"

cache: yarn

before_script:
  - yarn add global firebase-tools
  - yarn add global @angular/cli

script:
  - ng build --prod

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy.sh

notifications:
  email:
    on_failure: $EMAIL
    on_success: $EMAIL
