import { Course } from './course';

export const COURSES: Course[] = [
  {
    _id: 1,
    title: 'Angular',
    category: 'Web',
    authority: 'Lynda.com',
    certificateNumber: 'abc123',
    completed: 'today',
    length: 'long',
    url: '#',
  },
  {
    _id: 2,
    title: 'Android',
    category: 'Adroid',
    authority: 'Lynda.com',
    certificateNumber: 'abc123',
    completed: 'today',
    length: 'long',
    url: '#',
  },
  {
    _id: 3,
    title: 'iOS',
    category: 'iOS',
    authority: 'Lynda.com',
    certificateNumber: 'abc123',
    completed: 'today',
    length: 'long',
    url: '#',
  },
  {
    _id: 4,
    title: 'Firebase',
    category: 'Web',
    authority: 'Lynda.com',
    certificateNumber: 'abc123',
    completed: 'today',
    length: 'long',
    url: '#',
  },
  {
    _id: 5,
    title: 'Kotlin',
    category: 'Android',
    authority: 'Lynda.com',
    certificateNumber: 'abc123',
    completed: 'today',
    length: 'long',
    url: '#',
  },
];
